cart/urls.py
from django.conf.urls import url

from products import views
from .views import cart_home, cart_update, checkout_home, checkout_done_view

app_name = 'cart'


urlpatterns =[
    url(r'^$',cart_home,name='home'),
#      url(r'^/(?P<pk>\d+)/$',ProductDetailView.as_view(),name='product-details'),
    url(r'^update/$',cart_update,name='update'),

    url(r'^checkout/success/$', checkout_done_view, name='success'),

    url(r'^checkout/$',checkout_home, name='checkout'),
]

products/urls.py
from django.conf.urls import url

from products import views
from products.views import (
        ProductListView,
        # ProductDetailView,
        ProductFeaturedListView,
        ProductFeaturedDetailView,
        ProductDetailSlugView,
        # ProductCategoryListView,
        # ProductCategoryDetailView,
        
        )

app_name = 'product'


urlpatterns =[
     url(r'^$',ProductListView.as_view(),name='product-view'),
#      url(r'^/(?P<pk>\d+)/$',ProductDetailView.as_view(),name='product-details'),
     
     url(r'^(?P<slug>[\w-]+)/$',ProductDetailSlugView.as_view(),name='product-details'),

     url(r'^featured/$',ProductFeaturedListView.as_view(),name='product-featured-view'),
     url(r'^featured/details/(?P<pk>\d+)/$',ProductFeaturedDetailView.as_view(),name='product-featured-details'),
     
#      url(r'^category/$', ProductCategoryListView.as_view(), name='category-list'),
#      url(r'^category/(?P<slug>[\w-]+)/$', ProductCategoryDetailView.as_view(), name='category-detail'),
     url(r'^category/(?P<slug>[\w-]+)/$', views.get_category, name='category-detail'),
     url(r'^category/(?P<slug>[\w-]+)/(?P<sub_slug>[\w-]+)/$', views.get_sub_category, name='subcategory-detail'),
     url(r'^category/(?P<slug>[\w-]+)/(?P<sub_slug>[\w-]+)/(?P<subsub_slug>[\w-]+)/$', views.get_sub_sub_category, name='subsubcategory-detail'),
     url(r'^brand/(?P<slug>[\w-]+)/$', views.get_brand, name='brand-detail'),

]

products/models.py
from django.db.models import Q
from random import randint
import random
import os
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from zeemart.utils import unique_slug_generator
from django.db.models import Count
# Create your models here.



# category



                

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(
            new_filename=new_filename, 
            final_filename=final_filename
            )


# category
class Category(models.Model):
    title        = models.CharField(max_length=120, blank=True, unique=True)
    slug         = models.SlugField(blank=True,unique=True)
    image       = models.ImageField(upload_to='products/', null=True, blank=True)

    def get_category_url(self):
        return reverse("product:category-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.slug
    
    
    def get_products(self):
        return Product.objects.filter(category__title = self.title)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


def category_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(category_pre_save_receiver, sender=Category)



#  subcategory
class SubCategory(models.Model):
    title        = models.CharField(max_length=120, blank=True, unique=True)
    slug         = models.SlugField(blank=True,unique=True)
    category     = models.ForeignKey(Category,default="", blank=True, null=True, on_delete=models.CASCADE)
    image       = models.ImageField(upload_to='products/', null=True, blank=True)

    def get_subcategory_url(self):
        return reverse("product:subcategory-detail", kwargs={"slug": self.category, "sub_slug": self.slug })
    
    def __str__(self):
        return self.slug
    
    class Meta:
        verbose_name = 'SubCategory'
        verbose_name_plural = 'SubCategories'
    
def subcategory_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(subcategory_pre_save_receiver, sender=SubCategory) 

#  sub-subcategory
class SubSubCategory(models.Model):
    title        = models.CharField(max_length=120, blank=True, unique=True)
    slug         = models.SlugField(blank=True,unique=True)
    category     = models.ForeignKey(Category,default="", blank=True, null=True, on_delete=models.CASCADE)
    subcategory  = models.ForeignKey(SubCategory,default="", blank=True, null=True, on_delete=models.CASCADE)
    image        = models.ImageField(upload_to='products/', null=True, blank=True)


    def get_subsubcategory_url(self):
        return reverse("product:subsubcategory-detail", kwargs={"slug": self.category, "sub_slug": self.subcategory ,"subsub_slug":self.slug })
    
    def __str__(self):
        return self.slug
    
    class Meta:
        verbose_name = 'SubSubCategory'
        verbose_name_plural = 'SubSubCategories'
    
def subsubcategory_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(subsubcategory_pre_save_receiver, sender=SubSubCategory) 


class Brand(models.Model):
    title        = models.CharField(max_length=120, blank=True, unique=True)
    slug         = models.SlugField(blank=True,unique=True)
    image        = models.ImageField(upload_to='products/', null=True, blank=True)


    def get_brand_url(self):
        return reverse("product:brand-detail", kwargs={"slug": self.slug})
    
    def __str__(self):
        return self.slug
    
    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'
    
def brand_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(brand_pre_save_receiver, sender=Brand) 





class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def search(self, query):
        lookups =( Q(title__icontains=query) | 
                  Q(description__icontains=query)|
                  Q(tag__title__icontains=query)|
                  Q(category__title__icontains=query) )
        return self.filter(lookups).distinct()

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self): #Product.objects.featured() 
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id) # Product.objects == self.get_queryset()
        if qs.count() == 1:
            return qs.first()
        return None


    def search(self,query):
        # lookups = Q(title__icontains=query) | Q(description__icontains=query)
        return self.get_queryset().active().search(query)

class Product(models.Model): 
    title       = models.CharField(max_length=120)
    slug        = models.SlugField(blank=True, unique=True)
    description = models.TextField()
    price       = models.DecimalField(decimal_places = 0, max_digits=10,default=0.00)
    old_price   = models.DecimalField(decimal_places = 0, max_digits=10, default=0.00, null=True, blank=True)
    image       = models.ImageField(upload_to='products/', null=True, blank=True)
    featured    = models.BooleanField(default=False)
    active      = models.BooleanField(default=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    category    = models.ForeignKey(Category, default="", related_name='Category', blank=True, null=True, on_delete=models.CASCADE)
    subcategory    = models.ForeignKey(SubCategory,default="", related_name='SubCategory', blank=True, null=True, on_delete=models.CASCADE)
    subsubcategory    = models.ForeignKey(SubSubCategory,default="", related_name='SubSubCategory', blank=True, null=True, on_delete=models.CASCADE)
    brand         = models.ForeignKey(Brand, default="",related_name='Brand', blank=True, null=True, on_delete=models.CASCADE)

  

    objects = ProductManager()

    def get_absolute_url(self):

        return reverse("product:product-details",kwargs={"slug":self.slug})
        
        # return "/products/{slug}".format(slug=self.slug)

    def __str__(self):
        return self.title

    @property
    def name(self):
        return self.title
    
    



def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)

class MoreImages(models.Model):
    # user = models.ForeignKey(User)
    product = models.ForeignKey(Product, related_name='images')
    image = models.ImageField(upload_to='products/', null=True, blank=True)

    class Meta:
        verbose_name = 'MoreImage'
        verbose_name_plural = 'MoreImages'

products/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Product, Category, SubCategory, SubSubCategory
from cart.models import Cart
from analytics.mixin import ObjectViewedMixin
from django.db.models import Count
from random import randint
from random import shuffle
# Create your views here.
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count




class ProductFeaturedListView(ListView):
    # queryset = Product.objects.all()
    template_name = "products/product_featured_list.html"


    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().featured()

   
    
class ProductFeaturedDetailView(ObjectViewedMixin, DetailView):
    # queryset = Product.objects.all().featured()
    template_name = "products/product_featured_details.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().featured()
    


class ProductListView(TemplateView):
    
    template_name = "products/product_list.html"
    
    def get_context_data(self, *args, **kwargs):
        # context = super(ProductListView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        product_list = list(Product.objects.all())
        shuffle(product_list)
        paginator = Paginator(product_list, 18)
        page = self.request.GET.get('page')

        category      = Category.objects.all()[:7]

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        

        context = { 'products':products,
                    'cart': cart_obj,
                    'category': category }

        print(products)
        return context
    

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
    #     cart_obj, new_obj = Cart.objects.new_or_get(self.request)
    #     category      = Category.objects.all()[:7]

    #     context['cart'] = cart_obj
    #     return context


    

class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()
    template_name = "products/product_details.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        featured_product = list(Product.objects.filter(featured = True))[:2]
        shuffle(featured_product)
        context['cart'] = cart_obj
        context['featured_product'] = featured_product
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        #instance = get_object_or_404(Product, slug=slug, active=True)
        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("wtf ")
        return instance
    
    
# class ProductCategoryListView(ListView):
#     template_name = "products/product_category_listview.html"
#     queryset      = Category.objects.all()[:6]



def get_brand(request,slug):
    pass      

def get_category(request, slug):
    category_product_list = list(Product.objects.filter(category__slug=slug))

    subcategory = SubCategory.objects.filter(category__slug=slug)
    category_name   = Category.objects.filter(slug = slug)[:1]

    shuffle(category_product_list)
    paginator = Paginator(category_product_list, 18)
    page = request.GET.get('page')

    try:
        category_product = paginator.page(page)
    except PageNotAnInteger:
        category_product = paginator.page(1)
    except EmptyPage:
        category_product = paginator.page(paginator.num_pages)


    context = {'category_product' : category_product, 
                'sub_category':subcategory,
                'category_name':category_name}
    return render(request,'products/product_category_detailview.html', context)


def get_sub_category(request, slug, sub_slug):
    sub_name = SubCategory.objects.filter(category__slug=slug, slug = sub_slug)[:1]
    sub_category_product_list = list(Product.objects.filter(category__slug=slug, subcategory__slug = sub_slug))
    shuffle(sub_category_product_list)
    paginator = Paginator(sub_category_product_list, 18)
    page = request.GET.get('page')

    try:
        sub_category_product = paginator.page(page)
    except PageNotAnInteger:
        sub_category_product = paginator.page(1)
    except EmptyPage:
        sub_category_product = paginator.page(paginator.num_pages)


    subcategory_name = SubSubCategory.objects.filter(category__slug=slug, subcategory__slug = sub_slug)
    context = {  'sub_category_product' : sub_category_product , 
                 'subcategory_name' : subcategory_name,
                 'sub_name':sub_name}
    return render(request, 'products/product_subcategory_detailview.html',context)


def get_sub_sub_category(request, slug, sub_slug, subsub_slug):
    subsub_category_product_list = list(Product.objects.filter(category__slug=slug, subcategory__slug = sub_slug, subsubcategory__slug = subsub_slug))
    shuffle(subsub_category_product_list)
    paginator = Paginator(subsub_category_product_list, 18)
    page = request.GET.get('page')

    try:
        subsub_category_product = paginator.page(page)
    except PageNotAnInteger:
        subsub_category_product = paginator.page(1)
    except EmptyPage:
        subsub_category_product = paginator.page(paginator.num_pages)



    subcategory_name = SubCategory.objects.filter(category__slug=slug)
    subsub_name = SubSubCategory.objects.filter(category__slug=slug, subcategory__slug = sub_slug, slug = subsub_slug)[:1]
    context = {  'subsub_category_product' : subsub_category_product , 
                'subcategory_name' : subcategory_name,
                'subsub_name':subsub_name}
    return render(request, 'products/product_subsubcategory_detailview.html',context)

products/templates/products/snippet/card.html

<div class="col-lg-4 col-md-4 col-sm-6 col-6">
  <figure class="card card-product">
    <div class="img-wrap">
      <a href="{{ instance.get_absolute_url }}">
        {% if instance.image %}
        <img src="{{instance.image.url}}" alt="{{ instance.title }} logo"> {% endif %}
    </div>
    <figcaption class="info-wrap">
      <a href="{{ instance.get_absolute_url }}" class="title">{{instance.title}}</a>
      <div class="action-wrap">
          {% include 'products/snippet/update-cart.html' with product=instance cart=cart %}
        <div class="price-wrap h5">
          <span class="price-new">₦{{instance.price}}</span>
          {% if instance.old_price and instance.old_price > instance.price %}
            <small><del class="price-old">₦{{instance.old_price}}</del></small>
          {% endif %}
        </div> <!-- price-wrap.// -->
      </div> <!-- action-wrap -->
    </figcaption>
  </figure> <!-- card // -->
</div>

products/templates/products/snippet/error.html
{% load staticfiles %}

<section class="section-main bg padding-y-sm">
        <div class="container">
            <div class='col-lg-4 col-md-6 col-sm-8 col-10'>
                <h5>Ops!!! </h5>
            </div>
            
            <div class="card-banner col-lg-4 col-md-6 col-sm-8 col-10 mx-auto">
                <div class="card-body" style="height:350px; background-image: url({% static 'images/banners/ops.jpg' %});"> </div>
            <div class="text-bottom"><h5 class="title">No Products Here Yet</h5></div>
        </div>
        
</section> 

products/templates/products/snippet/featured_small_card.html
<div class="col-md-12 col-sm-6 col-xs-6">
    <figure class="item border-bottom mb-3">
        <a href="{{ instance.get_absolute_url }}" class="img-wrap">
         {% if instance.image %}
            <img src="{{instance.image.url}}" class="img-md"></a>
        {% endif %}
        <figcaption class="info-wrap">
            <a href="{{ instance.get_absolute_url }}" class="title">{{instance.title}}</a>
            <div class="price-wrap mb-3">
                <span class="price-new">₦{{instance.price}}</span>
                {% if instance.old_price and instance.old_price > instance.price %}
                 <small><del class="price-old">₦{{instance.old_price}}</del></small>
                {% endif %}
            </div> <!-- price-wrap.// -->
        </figcaption>
    </figure> <!-- card-product // -->
</div> <!-- col.// -->

products/templates/products/snippet/filter_section.html
<div class="card card-filter">
        <article class="card-group-item">
            <header class="card-header">
                <a class="" aria-expanded="true" href="#" data-toggle="collapse" data-target="#collapse22">
                    <i class="icon-action fa fa-chevron-down"></i>
                    <h6 class="title">{{ instance.title }}</h6>
                </a>
            </header>
            <div style="" class="filter-content collapse show" id="collapse22">
                <div class="card-body">
                    <!-- <form class="pb-3">
                        <div class="input-group">
                            <input class="form-control" placeholder="Search" type="text">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </form> -->

                    <ul class="list-unstyled list-lg">
                        <li><a href="#">Men <span class="float-right badge badge-light round">142</span>
                            </a></li>
                        <!-- <li><a href="#">Dapibus ac facilisis <span class="float-right badge badge-light round">3</span>
                            </a></li>
                        <li><a href="#">Morbi leo risus <span class="float-right badge badge-light round">32</span>
                            </a></li>
                        <li><a href="#">Another item <span class="float-right badge badge-light round">12</span>
                            </a></li> -->
                    </ul>
                </div> <!-- card-body.// -->
            </div> <!-- collapse .// -->
        </article> <!-- card-group-item.// -->
        
        <article class="card-group-item">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse44">
                    <i class="icon-action fa fa-chevron-down"></i>
                    <h6 class="title">By Feature </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse44">
                <div class="card-body">
                    <form>
                        <label class="form-check">
                            <input class="form-check-input" value="" type="checkbox">
                            <span class="form-check-label">
                                <span class="float-right badge badge-light round">5</span>
                                Samsung
                            </span>
                        </label> <!-- form-check.// -->
                        <!-- <label class="form-check">
                            <input class="form-check-input" value="" type="checkbox">
                            <span class="form-check-label">
                                <span class="float-right badge badge-light round">13</span>
                                Mersedes Benz
                            </span>
                        </label> form-check.// -->
                        
                         <!-- form-check.// -->
                    </form>
                </div> <!-- card-body.// -->
            </div> <!-- collapse .// -->
        </article> <!-- card-group-item.// -->

        <article class="card-group-item">
                <header class="card-header">
                    <a href="#" data-toggle="collapse" data-target="#collapse33">
                        <i class="icon-action fa fa-chevron-down"></i>
                        <h6 class="title">By Price </h6>
                    </a>
                </header>
                <div class="filter-content collapse show" id="collapse33">
                    <div class="card-body">
                        <input type="range" class="custom-range" min="0" max="100" name="">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Min</label>
                                <input class="form-control" placeholder="₦0" type="number">
                            </div>
                            <div class="form-group text-right col-md-6">
                                <label>Max</label>
                                <input class="form-control" placeholder="₦100,0000" type="number">
                            </div>
                        </div> <!-- form-row.// -->
                        <button class="btn btn-block btn-outline-primary">Apply</button>
                    </div> <!-- card-body.// -->
                </div> <!-- collapse .// -->
            </article> <!-- card-group-item.// -->
    </div> <!-- card.// -->

products/templates/products/snippet/paginator.html

        <nav class="mt-5">
            <ul class="pagination justify-content-center"> 
            {% if paginate.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                    <li class="page-item ">
          
                        <a class="page-link" href="?page={{ paginate.previous_page_number }}"><i class="glyphicon glyphicon-chevron-left">Prev</i></a>
                        
                    </li>
            {% endif %}
              <!-- <li class="page-item active"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li> -->

               <div class="card" style="margin-left: 5px; margin-top: 2px; margin-right: 5px">
                    <h6 style="margin-left: 15px; margin-top: 5px; margin-right: 6px">
                        <small> 
                            Page {{ paginate.number }} of {{ paginate.paginator.num_pages }}  
                        </small>
                    </h6> 
                   
                </div>
               
              
            
            {% if paginate.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ paginate.next_page_number }}"><i class="glyphicon glyphicon-chevron-right"></i>Next</a></li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ paginate.paginator.num_pages }}">Last</a>
                </li>
            {% endif %}
            </ul>

    </nav>
         

products/templates/products/snippet/update-cart.html
<form class='form-product-ajax' method='POST' action='{% url "cart:update" %}' data-endpoint='{% url "cart:update" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ product.id }}' />
      <span class='submit-span'>
    {% if product in cart.products.all %}
        In cart <button type='submit' class='btn btn-link btn-sm float-right'>Remove?</button>
    {% else %}
        <button type='submit'  class='btn btn-outline-primary btn-sm float-right'>Add to cart</button>
    {% endif %}
    </span>
</form>

