cart/urls.py
from django.conf.urls import url

from products import views
from .views import cart_home, cart_update, checkout_home, checkout_done_view

app_name = 'cart'


urlpatterns =[
    url(r'^$',cart_home,name='home'),
#      url(r'^/(?P<pk>\d+)/$',ProductDetailView.as_view(),name='product-details'),
    url(r'^update/$',cart_update,name='update'),

    url(r'^checkout/success/$', checkout_done_view, name='success'),

    url(r'^checkout/$',checkout_home, name='checkout'),
]

cart/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings
from products.models import Product 
from django.db.models.signals import pre_save, post_save, m2m_changed


# Create your models here.

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user        = models.ForeignKey(User, null=True,blank=True)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    

    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)




def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

cart/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse

from .models import Cart
from products.models import Product
from order.models import Order
from main.forms import LoginForm
from billing.models import BillingProfile
from address.forms import AddressForm
from address.models import Address

# Create your views here.



def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
            "id": x.id,
            "url": x.get_absolute_url(),
            "image": x.image.url,
            "name": x.name, 
            "price": x.price
            } 
            for x in cart_obj.products.all()]
    cart_data  = {"products": products, "subtotal": cart_obj.subtotal, "total": cart_obj.total}
    return JsonResponse(cart_data)


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
   
    return render(request, "cart/home.html", {"cart":cart_obj})



def cart_update(request):
    product_id = request.POST.get('product_id')
    # if request.is_ajax():
    #     print("Ajax request")
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added = False
        else:
            cart_obj.products.add(product_obj) 
            added = True
        request.session['cart_items'] = cart_obj.products.count()
        if request.is_ajax(): # Asynchronous JavaScript And XML / JSON
            print("Ajax request")
            json_data = {
                "added": added,
                "removed": not added,
                "cartItemCount":cart_obj.products.count()
            }
            return JsonResponse(json_data, status=200)
    return redirect("cart:home")

def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")
    
    login_form = LoginForm()
    address_form = AddressForm()

    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)
   
    
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None

    if billing_profile is not None:
        if request.user.is_authenticated():
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id) 
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        "check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")

    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "address_form":address_form,
        "address_qs": address_qs,
    }
    return render(request, "cart/checkout.html", context)


def checkout_done_view(request):
    return render(request, "cart/checkout-done.html", {})

cart/templates/cart/checkout-done.html
{% extends "base.html" %}


{% block content %}
<div class='col-6 mx-auto py-5 text-center'>
  <h1 class='display-1'>Thank you for your order!!!</h1>
</div>

{% endblock %}

cart/templates/cart/checkout.html
{% extends "base.html" %}

{% load staticfiles %}
{% block content %}

{% block style %}
    <link href='{% static "css/register.css" %}' rel="stylesheet">
{% endblock %}

<div class="container"> 

        {{ object.order_id }} -- {{ object.cart }}
        {% if not billing_profile %}
            <div class='row'>
                {{ object.order_id }} -- {{ object.cart }}
                
                <div class='col-lg-12 col-md-12'>
                    {% include 'main/snippet/form.html' with form=login_form next_url=request.build_absolute_uri %}
                </div>

            </div>

        {% else %}
            <!-- <h1>Checkout</h1>

            <p>Cart Total: {{ object.cart.total }}</p>
            <p>Shipping Total: {{ object.shipping_total }}</p>
            <p>Order Total: {{ object.total }}</p> -->

            {{ object.order_id }} -- {{ object.cart }}


            {% if not object.shipping_address %}

                <div class='row'>
                    <div class='card col-lg-4 col-md-6 col-sm-8 col-10 mx-auto' id="card">
                        <article class="card-body">

                            <h4 class="card-title mb-4 mt-1">Shipping Address</h4>
                                        
                            {% url "checkout_address_create" as checkout_address_create %}
                            {% include 'address/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
                        </article>
                           
                    </div>

                    <div class='col-6'>
                        {% url 'checkout_address_reuse' as checkout_address_reuse %}
                        {% include 'address/prev_address.html' with address_qs=address_qs next_url=request.build_absolute_uri  address_type='shipping' action_url=checkout_address_reuse %}
                    </div>
                </div>


                {% elif not object.billing_address %}
                <div class='row'>
                    <div class='card col-lg-4 col-md-6 col-sm-8 col-10 mx-auto'>
                        <article class="card-body">

                            <h4 class="card-title mb-4 mt-1">Billing Address</h4>
                                
                            {% url "checkout_address_create" as checkout_address_create %}
                            {% include 'address/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
                        </article>
                    </div>
                

                    <div class='col-6'>
                        {% url 'checkout_address_reuse' as checkout_address_reuse %}
                        {% include 'address/prev_address.html' with address_qs=address_qs next_url=request.build_absolute_uri  address_type='billing' action_url=checkout_address_reuse %}
                    </div>
                </div>
                {% else %}

                <h1>Finalize Checkout</h1>
                <p>Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                <p>Shipping Address: {{ object.shipping_address.get_address }}</p>
                <p>Billing Address: {{ object.shipping_address.get_address }}</p>
                <p>Cart Total: {{ object.cart.total }}</p>
                <p>Shipping Total: {{ object.shipping_total }}</p>
                <p>Order Total: {{ object.total }}</p>
                <form class='form' method='POST' action="">{% csrf_token %}
                    <button type='submit' class='btn btn-outline-primary'>Checkout</button>
                </form> 
            {% endif %}
        {% endif %}
</div>









{% endblock %}

cart/templates/cart/home.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block style %}
    <link href='{% static "css/cart.css" %}' rel="stylesheet">
{% endblock %}


  {% block content %} 
    
  <div class="container">
      <h1>Cart</h1>
      

    {% if cart.products.exists %}
    <div class="card">
      <table class="table table-hover shopping-cart-wrap cart-table">
        <thead class="text-muted">
          <tr>
            <th scope="col" width="400">Product</th>
            <th scope="col" width="120">Quantity</th>
            <th scope="col" width="120">Price</th>
            <th scope="col" width="200" class="text-right">Action</th>
          </tr>
        </thead>
        <tbody class='cart-body'>
          {% for product in cart.products.all %}
          <tr class='cart-product'>
            <td>

                <figure class="media">
                    <div class="img-wrap"><img src="{{ product.image.url }}" class="img-thumbnail img-sm"></div>
                    <figcaption class="media-body">
                      <a href='{{ product.get_absolute_url }}' ><h6 class="title text-truncate">{{ product.title }}</h6></a>
                      <!-- <dl class="dlist-inline small">
                        <dt>Size: </dt>
                        <dd>XXL</dd>
                      </dl>
                      <dl class="dlist-inline small">
                        <dt>Color: </dt>
                        <dd>Orange color</dd>
                      </dl> -->
                    </figcaption>
                </figure>
              
              

              <!-- {% include 'products/snippet/update-cart.html' with product=product cart=cart in_cart=True %} -->
            </td>
            <td>
                <select class="form-control">
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                </select>
            </td>
            <td>
              <div class="price-wrap">
                  <var class="price">₦{{ product.price }}</var>
                  <small class="text-muted">(Naira each)</small>
              </div> <!-- price-wrap .// -->
            </td>
            <td class="text-right">
              {% include 'cart/snippet/remove-product.html' with product_id=product.id %}
            </td>
          </tr>
          {% endfor %}
          <tr>
            <td colspan="2"></td>
            <td><b>Subtotal</b>₦<span class='cart-subtotal'>{{ cart.subtotal }}</span> </td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td><b>Total</b> ₦<span class='cart-total'> {{ cart.total }}</span></td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td><a class='btn btn-md btn-outline-primary' href='{% url "cart:checkout" %}'>Checkout</a></td>
          </tr>

        </tbody>
      </table>
    </div>

    <div class='cart-item-remove-form' style='display:none'>

      {% include 'cart/snippet/remove-product.html' %}
    </div>

    {% else %}
    <p class='lead'>Cart is empty</p>
    {% endif %}
  </div>

            

       

      

          <!-- <div class="totals">
              <div class="totals-item">
                <label>Subtotal</label>
                <div class="totals-value" id="cart-subtotal">71.97</div>
              </div>
              <div class="totals-item">
                <label>Tax (5%)</label>
                <div class="totals-value" id="cart-tax">3.60</div>
              </div>
              <div class="totals-item">
                <label>Shipping</label>
                <div class="totals-value" id="cart-shipping">15.00</div>
              </div>
              <div class="totals-item totals-item-total">
                <label>Grand Total</label>
                <div class="totals-value" id="cart-total">90.57</div>
              </div>
            </div>
                
                <button class="checkout">Checkout</button>
          
          </div> -->

   

{% endblock %}



  



cart/templates/cart/html.html






        {% if cart.products.exists %}
          <div class="card">
            <table class="table table-hover shopping-cart-wrap cart-table">
              <thead class="text-muted">
                <tr>
          
                  <th scope="col">Product</th>
                  <th scope="col" width="120">Quantity</th>
                  <th scope="col" width="120">Price</th>
                  <th scope="col" width="200" class="text-right">Action</th>
                </tr>
              </thead>
              <tbody class='cart-body'>
              {% for product in cart.products.all %}
                <tr class='cart-product'>
                  <td>
                    <figure class="media">
                      <div class="img-wrap"><img src="{{ product.image.url }}" class="img-thumbnail img-sm"></div>
                      <figcaption class="media-body">
                        <a href='{{ product.get_absolute_url }}' ><h6 class="title text-truncate">{{ product.title }}</h6></a>
                        <!-- <dl class="dlist-inline small">
                          <dt>Size: </dt>
                          <dd>XXL</dd>
                        </dl>
                        <dl class="dlist-inline small">
                          <dt>Color: </dt>
                          <dd>Orange color</dd>
                        </dl> -->
                      </figcaption>
                    </figure>
                  </td>
                  <td>
                    <select class="form-control">
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                      <option>4</option>
                    </select>
                  </td>
                  <td>
                    <div class="price-wrap">
                      <var class="price"># {{ product.price }}</var>
                      <small class="text-muted">(Naira each)</small>
                    </div> <!-- price-wrap .// -->
                  </td>
                  <td class="text-right">
                     <!-- <a title="" href="" class="btn btn-outline-success" data-toggle="tooltip" data-original-title="Save to Wishlist"> <i
                        class="fa fa-heart"></i></a> -->
                    <!-- <a href="" class="btn btn-outline-danger"> × Remove</a> -->
                    {% include 'cart/snippet/remove-product.html' with product_id=product.id %}
                   
                  </td>
                  
                </tr>
              {% endfor %}

              
                
            </tbody>
            </table>
          </div> <!-- card.// -->
         

          <div class="container">
            <table class="table cart-table">
              <tbody class='cart-body'>
                <tr>
                    <td colspan="2"></td>
                    <td><b>Subtotal</b>#<span class='cart-subtotal'>{{ cart.subtotal }}</span> </td>
                  </tr>
                  <tr>
                    <td colspan="2"></td>
                    <td><b>Total</b> #<span class='cart-total'> {{ cart.total }}</span></td>
                  </tr>
                  <tr>
                    <td colspan="2"></td>
                    <td><a class='btn btn-lg btn-success' href='{% url "cart:checkout" %}'>Checkout</a></td>
                </tr>
              </tbody>
            </table>

          </div>
            
          
          <div class='cart-item-remove-form' style='display:none'>

            {% include 'cart/snippet/remove-product.html' %}
          </div>

          {% else %}
            <p class='lead'>Cart is empty</p>
          {% endif %}




          <!-- jjjrrrrrrrrrrrrrrrrrrrrrrrrrr -->

          {% if cart.products.exists %}
      <table class="table cart-table">
        <thead>
          <tr>
            <th>#</th>
            <th>Product Name</th>
            <th>Product Price</th>
          </tr>
        </thead>
        <tbody class='cart-body'>
          {% for product in cart.products.all %}
          <tr class='cart-product'>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href='{{ product.get_absolute_url }}'>{{ product.title }}</a>


              <!-- {% include 'products/snippet/update-cart.html' with product=product cart=cart in_cart=True %} -->
              {% include 'cart/snippet/remove-product.html' with product_id=product.id %}
            </td>
            <td>{{ product.price }}</td>
          </tr>
          {% endfor %}
          <tr>
            <td colspan="2"></td>
            <td><b>Subtotal</b>$<span class='cart-subtotal'>{{ cart.subtotal }}</span> </td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td><b>Total</b> $<span class='cart-total'> {{ cart.total }}</span></td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td><a class='btn btn-lg btn-success' href='{% url "cart:checkout" %}'>Checkout</a></td>
          </tr>

        </tbody>
      </table>

      <div class='cart-item-remove-form' style='display:none'>

        {% include 'cart/snippet/remove-product.html' %}
      </div>

      {% else %}
      <p class='lead'>Cart is empty</p>
      {% endif %}



      <!-- cartBody.prepend("<tr><th scope=\"row\">" + i + "</th><td><a href='" + value.url + "'>" + value.name + "</a>" + newCartItemRemove.html() + "</td><td>" + value.price + "</td> </tr>")
                i -- -->