cart/urls.py
from django.conf.urls import url

from products import views
from .views import cart_home, cart_update, checkout_home, checkout_done_view

app_name = 'cart'


urlpatterns =[
    url(r'^$',cart_home,name='home'),
#      url(r'^/(?P<pk>\d+)/$',ProductDetailView.as_view(),name='product-details'),
    url(r'^update/$',cart_update,name='update'),

    url(r'^checkout/success/$', checkout_done_view, name='success'),

    url(r'^checkout/$',checkout_home, name='checkout'),
]

main/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from .import views
from django.contrib.auth.views import login,logout
from main.views import IndexView, LoginView

from django.contrib.auth.views import(
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
    LogoutView
    
)



app_name = 'main'


urlpatterns =[
    url(r'^$', IndexView.as_view(), name='index'),
  
    # url(r'^login/$',login,{'template_name':'main/login.html'},name='login'),

    url(r'^login/$',LoginView.as_view(),name='login'),

    # url(r'^login/$',views.login_page,name='login'),

    url(r'^logout/$',logout,{'template_name':'main/index.html'},name='logout'),

    # url(r'^logout/$',LogoutView.as_view(),name='logout'),

    url(r'^register/$', views.register, name='register'),

    url(r'^change-password/$',views.change_password, name="change_password"),
   
    url(r'^customer-profile/$',views.customer_profile, name="customer_profile"),
    
    url(r'^reset-password/$', password_reset, {'template_name':'main/reset_password.html',
                                                    'email_template_name':'main/reset_password_email.html',
                                                    'post_reset_redirect':'main:password_reset_done',
                                                    'from_email':'main@django.com',},name='password_reset'),

   
    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'main/reset_password_done.html'},
                                                         name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm, {'template_name':'main/reset_password_confirm.html',
                              'post_reset_redirect': reverse_lazy('main:password_reset_complete')},
                              name='password_reset_confirm'),

    url(r'reset-password/complete/$', password_reset_complete,{'template_name':'main/reset_password_complete.html'}, name='password_reset_complete'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save

# Create your models here.

class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError('The given must be email')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user 

    def create_user(self, email, password=None, **extra_fields):

        extra_fields.setdefault('is_staff',False)
        extra_fields.setdefault('is_superuser',False)
        return self._create_user(email, password, **extra_fields) 

    def create_superuser(self, email, password, **extra_fields):

        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_superuser',True)


        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')  
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.') 

        return self._create_user(email,password, **extra_fields)   

#User Model
class User(AbstractUser):

    
    # description = models.CharField(max_length=200, default='')
    # city = models.CharField( max_length=200,default='')

    username = None
    email = models.EmailField(_('email address'),unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


    objects = UserManager()

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.PROTECT)
    address = models.CharField(blank=True,max_length=200)
    city = models.CharField(blank=True,max_length=200)
    state = models.CharField(blank=True,max_length=200)
    phone_number = models.IntegerField(blank=True,default='0')
    


    def __str__(self):
        return self.user.email

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile,sender=User)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile, User
from django.contrib.auth import get_user_model



User = get_user_model()


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        for fieldname in ['password1', 'password2']:
            self.fields[fieldname].help_text = None


    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    # save user method
    def save(self, commit=True):
        user = super(RegistrationForm,self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']    

        if commit:
            user.save()

        return user 

class UpdateCustomerForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
        )


class UpdateCustomerFormTwo(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields =(
            'address',
            'city',
            'state',
            'phone_number'
        )

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

main/views.py
from django.shortcuts import render
from django.utils.http import is_safe_url
from django.views.generic import TemplateView, CreateView, FormView
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from .models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from .forms import RegistrationForm, UpdateCustomerForm,UpdateCustomerFormTwo,LoginForm
from .signals import user_logged_in
from products.models import Category, SubCategory,SubSubCategory, Product
from random import shuffle
import random
from django.db.models import Max
# Create your views here.
# def home_page(request):
#     return render(request, "home_page.html", {})

class IndexView(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self,*args, **kwargs):
        category      = Category.objects.all()[:7]
        subcategory   = SubCategory.objects.all()
        subsubcategory  = SubSubCategory.objects.all()
        featured_product = list(Product.objects.filter(featured = True))
        shuffle(featured_product)

        context = { 'category':category,
                'subcategory': subcategory,
                'subsubcategory': subsubcategory,
                'featured_product': featured_product }
        return context
    

    
            
    

def subcategory_list(request, slug):
    subcategory   = SubCategory.objects.filter(category__slug=slug)
    print(subcategory)
    # category      = Category.objects.all()[:7]
    context = {'subcategory': subcategory}
    return render(request,'main/index.html', context)

    



def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST) #from our registration form class in form.py, we get the request method

        if form.is_valid():
            form.save()

            email = request.POST.get('email')
            password = request.POST.get('password1')


            user = authenticate(
                request,
                email = email,
                password = password
            )
            login(request, user)
            return redirect(reverse('main:index'))
    else:
        form = RegistrationForm()
    args = {'form':form} 
    return render(request, 'main/reg_form.html',args) 


def customer_profile(request):
    if request.method == "POST":
        form = UpdateCustomerForm(request.POST, instance=request.user,prefix='form')
        form2 = UpdateCustomerFormTwo(request.POST,instance=request.user.userprofile, prefix='form2')

        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return redirect(reverse('main:customer_profile'))
        else:
            return render(request,'main/customer_profile.html',{'form':form, 'form2':form2})
    else:
        form = UpdateCustomerForm(instance = request.user,prefix='form')
        form2 = UpdateCustomerFormTwo(instance = request.user.userprofile,prefix='form2')
        args = {'form':form,'form2':form2}
        return render(request,'main/customer_profile.html',args)




def change_password(request):
    
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user = request.user)
        if form.is_valid():
            form.save()
            messages.success(request,"Your new password has been saved")
            update_session_auth_hash(request,form.user)
            return redirect(reverse('main:profile'))

    else:
        form = PasswordChangeForm(user=request.user)
    args = {'form':form}
    return render(request,'main/change_password.html', args)     


class LoginView(FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'main/login.html'

    def form_valid(self, form):
        request = self.request
        next_ = request.GET.get('next')
        next_post = request.POST.get('next')
        redirect_path = next_ or next_post or None
        email  = form.cleaned_data.get("email")
        password  = form.cleaned_data.get("password")
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            user_logged_in.send(user.__class__, instance=user, request=request)
            if is_safe_url(redirect_path, request.get_host()):
                return redirect(redirect_path)
            else:
                return redirect("/")
        return super(LoginView, self).form_invalid(form)

main/templates/main/category_sections.html
{% if category %}
    {% for item in category %}

        <section class="section-content padding-y-sm bg">
            <div class="container">

                <header class="section-heading heading-line">
                    <h4 class="title-section bg">{{ item.title }}</h4>
                </header>

                <div class="card">
                    <div class="row no-gutters">
                        <div class="col-md-3">
                            <div class="card-banner align-items-end" {% if item.image %}  style="height:295px; background-image: url('{{item.image.url}}'); border-radius:0;" {% endif %}>
                                
                                    <article class="overlay m-4 w-100">
                                        <h5 class="card-title">{{ item.title }}</h5>
                                        <a href="{{ item.get_category_url }}" class="btn btn-primary btn-sm"> View more </a>
                                    </article>
                            </div> <!-- card.// -->
                        </div>
                        <!-- col.// -->
                        <div class="col-md-9">
                            <ul class="row no-gutters border-cols">
                            {% if subcategory %}
                                {% for sub in subcategory %}
                                    {% if item == sub.category %}
                                        
                                            {% include 'main/snippet/categories_small_card.html' %}
                                        
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            
                            </ul>
                        </div>
                        <!-- col.// -->
                    </div>
                    <!-- row.// -->

                </div>
                <!-- card.// -->

            </div>
            <!-- container .//  -->
        </section>
    {% endfor %}

{% endif %}

main/templates/main/change_password.html
{% extends "base.html" %}

 {% load staticfiles %}
 {% load crispy_forms_tags %}

    {% block style %}
        <link href='{% static "css/register.css" %}' rel="stylesheet">
    {% endblock %}


    {% block content %}   

    <div class="container">
   

        <div class="row">

       
                <div class="card col-lg-4 col-md-6 col-sm-8 col-10 mx-auto" id="card">
                    <article class="card-body">
                   
                    <h4 class="card-title mb-4 mt-1">Change Password</h4>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }} 
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Update Password  </button>
                        </div> <!-- form-group// -->                                                           
                    </form>
                    </article>
                </div> <!-- card.// -->
    
            
    
    
        </div>
    </div>
    {% endblock %}

main/templates/main/customer_profile.html
{% extends "base.html" %}

{% load staticfiles %}

{% load crispy_forms_tags %}

{% block style %}
    <link href='{% static "css/customer_profile.css" %}' rel="stylesheet">
{% endblock %}


   {% block content %}   

   <div class="container">
       
       <div class="row">

       
            <div class="card col-lg-4 col-md-6 col-sm-8 col-10" id="card">
                <article class="card-body">
                <h4 class="card-title mb-4 mt-1">{{ request.user.first_name }}</h4>
                <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
             
                        {{request.user.email}}
                        <br/>
                        <br/>
                        <br/>
                        
                        {{ form2|crispy }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Update  </button>
                    </div> <!-- form-group// -->                                                           
                </form>
                </article>
            </div> <!-- card.// -->


            
            <div class="box col-6">
                    <dl class="dlist-align">
                    <dt>Some info: </dt>
                    <dd> Everything in this life is always tempporary</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt>Parameter: </dt>
                    <dd>Value name</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt>Color:</dt>
                    <dd>Orange and Black</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt>Material:</dt>
                    <dd>Leather</dd>
                    </dl>
                    </div> <!-- box.// -->
                    

                    


            </div>
   </div>
   {% endblock %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block style %}
    <link href='{% static "css/login.css" %}' rel="stylesheet">
{% endblock %}


{% block content %}   


<div class="container">


    <div class="row">

       
            <div class="card col-lg-4 col-md-6 col-sm-8 col-10 mx-auto" id="card">
                <article class="card-body">
                <a href="{% url 'main:register' %}" class="float-right btn btn-outline-primary">Sign up</a>
                <h4 class="card-title mb-4 mt-1">Sign in</h4>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }} 
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Login  </button>
                    </div> <!-- form-group// -->                                                           
                </form>

                <a href="{% url 'main:password_reset' %}"><small >Forgot Password? </small></a>
                </article>
            </div> <!-- card.// -->

        


    </div>
        
        
   

   
</div>

 

{% endblock %}   

main/templates/main/logout.html
{% extends 'base.html' %}
 {% load staticfiles %}

{% block content %}
    <div class="container">
        <h2>You have logged out</h2>
    </div>

{% endblock %}

main/templates/main/reg_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block style %}
    <link href='{% static "css/register.css" %}' rel="stylesheet">
{% endblock %}


{% block content %}   


<div class="container">

        <div class="row">

       
                <div class="card col-lg-4 col-md-6 col-sm-8 col-10 mx-auto" id="card">
                    <article class="card-body">
                    <a href="{% url 'main:login' %}" class="float-right btn btn-outline-primary">Login</a>
                    <h4 class="card-title mb-4 mt-1">Sign Up</h4>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }} 
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Sign Up  </button>
                        </div> <!-- form-group// -->                                                           
                    </form>
                    </article>
                </div> <!-- card.// -->
    
            
    
    
        </div>
</div>


{% endblock %}     

main/templates/main/reset_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block style %}
    <link href='{% static "css/register.css" %}' rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">


    <div class="row">

       
            <div class="card col-lg-4 col-md-6 col-sm-8 col-10 mx-auto" id="card">
                <article class="card-body">
                
                <h4 class="card-title mb-4 mt-1">Password reset</h4>

                <h5>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</h5>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }} 
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Reset password  </button>
                    </div> <!-- form-group// -->                                                           
                </form>
                </article>
            </div> <!-- card.// -->

        


    </div>
</div>
{% endblock %}

main/templates/main/reset_password_complete.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %}
    <link href='{% static "css/register.css" %}' rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">

        <div class="row">

       
            <div class="card col-lg-4 col-md-6 col-sm-8 col-10 mx-auto" id="card">
                <article class="card-body">
               
                <h4 class="card-title mb-4 mt-1">Password reset complete </h4>
                
                  <p>
                    You can now login 
                  </p>
                
                    <div class="form-group">
                        <a href="{% url 'main:login' %}">  <button type="submit" class="btn btn-primary btn-block"> Login  </button></a>
                    </div> <!-- form-group// -->                                                           
                
                </article>
            </div> <!-- card.// -->

        


    </div>


</div>
{% endblock %}

main/templates/main/reset_password_confirm.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block style %}
    <link href='{% static "css/register.css" %}' rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
   

    <div class="row">

       
            <div class="card col-lg-4 col-md-6 col-sm-8 col-10 mx-auto" id="card">
                <article class="card-body">
                
                <h4 class="card-title mb-4 mt-1">Password confirm</h4>

                <h5>Please Enter a New Password</h5>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }} 
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Reset password  </button>
                    </div> <!-- form-group// -->                                                           
                </form>
                </article>
            </div> <!-- card.// -->

        


    </div>


</div>
{% endblock %}

main/templates/main/reset_password_done.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %}
    <link href='{% static "css/register.css" %}' rel="stylesheet">
{% endblock %}

{% block content %}


<div class="container">

    <div class="row">

       
      <div class="card col-8 mx-auto" id="card">
                <article class="card-body">
                
                <h4 class="card-title mb-4 mt-1">Password reset sent</h4>
                  <p>
                    We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
          
                    If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder
          
                  </p>
                
                </article>
      </div> <!-- card.// -->

        


    </div>

</div>
{% endblock %}

main/templates/main/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'main:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
	
{% trans "Thanks for using our site!" %}
	
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
	
{% endautoescape %}